name: Run Gradle test

on:
  push:
    branches:
      - main
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - uses: eskatos/gradle-command-action@v1
      name: gradle test
      with:
        arguments: test jacocoTestReport
      env:
        OXFORDKEY: ${{secrets.OXFORDKEY}}
        OXFORDID: ${{secrets.OXFORDID}}
    - name: Coveralls Test Report
      run: ./gradlew coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        CI_NAME: Github Actions
        CI_BRANCH: ${{github.ref}}
        CI_PULL_REQUEST: ${{github.event.pull_request.html_url}}